'user client';
import Head from 'next/head'
import { Inter } from '@next/font/google'
import { ChakraProvider } from '@chakra-ui/react'
import Quaters from './Quaters';
const inter = Inter({ subsets: ['latin'] })
import Hero from './Hero'

import Quarter1 from './Quarter1';
export default function Home() {
  return (
    <>
      <ChakraProvider>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
     
        <Hero />
        <Quaters/>
        <Quarter1/>
      </ChakraProvider>


    </>
  )
}
